[package]
name = "linoleum"
version = "0.1.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
build = "build.rs"

[dependencies]
ahi = { git = "https://github.com/mdsteele/ahi" }
getopts = "0.2"
sdl2 = { version = "0.24", features = ["use_mac_framework"] }
